path:
  ckpt_path: "./output/ckpt/AISHELL3_ecapa_fintuning"
  log_path: "./output/log/AISHELL3_ecapa_fintuning"
  result_path: "./output/result/AISHELL3_ecapa_fintuning"

optimizer:
  batch_size: 2
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
# step:
#   total_step: 4000000
#   log_step: 100
#   synth_step: 1000
#   val_step: 1000
#   save_step: 50000# 
step:
  total_step: 2000100
  log_step: 1
  synth_step: 5
  val_step: 5
  save_step: 20

